"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gi5bey_j#6o49+l(2d-)126nam^qtwt4b^z=t$sb(a$ig-d9zi'

# セキュリティ警告: 本番環境ではデバッグを有効にした状態で実行しないでください！
DEBUG = False

# サーバーのパブリックIPアドレスを許可リストに追加します
ALLOWED_HOSTS = ['132.145.126.81', 'localhost', '127.0.0.1', 'puripurigames.mydns.jp']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kakeibo',  # これを追加した
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

WALLET_DIR = '/home/opc/kakeibo/kakeibo-backend/kakeibo/wallet'  # ウォレットのディレクトリを指定

# config/settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'puri2db_high',
        'USER': 'ADMIN',
        'PASSWORD': 'Puri^2Games0228',
        'CONN_MAX_AGE': 0,
        'OPTIONS': {
            'config_dir': '/home/opc/kakeibo/kakeibo-backend/kakeibo/wallet',
            'wallet_location': '/home/opc/kakeibo/kakeibo-backend/kakeibo/wallet',
            # 空文字、またはウォレット作成時のパスワード（もしあれば）をここに仕込むことで、
            # Djangoが自動的にウォレットを読み込むようにする
            'wallet_password': 'Puri^2Games0228', 
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# コマンドを叩いた時に、Django内部のCSSをここに集約するという「絶対パス」の指定
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework のグローバル設定を追加
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        # 画面表示（HTML）をあきらめて、純粋なJSONだけを返すように強制します
        'rest_framework.renderers.JSONRenderer',
    ]
}

# ログイン成功時・ログアウト時のリダイレクト先URL
LOGIN_REDIRECT_URL = '/api/expenses/'
LOGOUT_REDIRECT_URL = '/'

# Nginx（プロキシ）経由のヘッダーをDjangoに正しく認識させる設定
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 信頼できるオリジン（アクセス元）として、サーバーのIPアドレスを登録
CSRF_TRUSTED_ORIGINS = [
    'http://132.145.126.81',
    'http://puripurigames.mydns.jp',
]