# Generated by Django 4.2.30 on 2026-06-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigIntegerField(db_column='CATEGORY_ID', primary_key=True, serialize=False)),
                ('category_name', models.CharField(db_column='CATEGORY_NAME', max_length=50)),
                ('db_update_date', models.DateTimeField(auto_now=True, db_column='DB_UPDATE_DATE')),
                ('db_update_user', models.CharField(db_column='DB_UPDATE_USER', max_length=50)),
                ('db_insert_date', models.DateTimeField(auto_now_add=True, db_column='DB_INSERT_DATE')),
                ('db_insert_user', models.CharField(db_column='DB_INSERT_USER', max_length=50)),
            ],
            options={
                'db_table': 'T_CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.BigIntegerField(db_column='MEMBER_ID', primary_key=True, serialize=False)),
                ('member_name', models.CharField(db_column='MEMBER_NAME', max_length=50)),
                ('db_update_date', models.DateTimeField(auto_now=True, db_column='DB_UPDATE_DATE')),
                ('db_update_user', models.CharField(db_column='DB_UPDATE_USER', max_length=50)),
                ('db_insert_date', models.DateTimeField(auto_now_add=True, db_column='DB_INSERT_DATE')),
                ('db_insert_user', models.CharField(db_column='DB_INSERT_USER', max_length=50)),
            ],
            options={
                'db_table': 'T_MEMBER',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expenses_id', models.BigIntegerField(db_column='EXPENSES_ID', primary_key=True, serialize=False)),
                ('use_date', models.DateField(db_column='USE_DATE')),
                ('shop', models.CharField(db_column='SHOP', max_length=255)),
                ('amount', models.IntegerField(db_column='AMOUNT')),
                ('memo', models.CharField(blank=True, db_column='MEMO', max_length=255, null=True)),
                ('is_closed', models.IntegerField(db_column='IS_CLOSED', default=0)),
                ('source_file', models.CharField(blank=True, db_column='SOURCE_FILE', max_length=255, null=True)),
                ('db_update_date', models.DateTimeField(auto_now=True, db_column='DB_UPDATE_DATE')),
                ('db_update_user', models.CharField(db_column='DB_UPDATE_USER', max_length=50)),
                ('db_insert_date', models.DateTimeField(auto_now_add=True, db_column='DB_INSERT_DATE')),
                ('db_insert_user', models.CharField(db_column='DB_INSERT_USER', max_length=50)),
                ('category', models.ForeignKey(blank=True, db_column='CATEGORY_ID', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.category')),
                ('member', models.ForeignKey(blank=True, db_column='MEMBER_ID', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.member')),
            ],
            options={
                'db_table': 'T_EXPENSES',
            },
        ),
    ]
