# Generated by Django 4.2.30 on 2026-06-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_alter_category_options_alter_expenses_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={},
        ),
    ]
