# Generated by Django 4.2.30 on 2026-06-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0003_alter_expenses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(db_column='AMOUNT', db_comment='金額'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(blank=True, db_column='CATEGORY_ID', db_comment='カテゴリID', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.category'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='db_insert_date',
            field=models.DateTimeField(auto_now_add=True, db_column='DB_INSERT_DATE', db_comment='DB登録日時'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='db_insert_user',
            field=models.CharField(db_column='DB_INSERT_USER', db_comment='DB登録者', max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='db_update_date',
            field=models.DateTimeField(auto_now=True, db_column='DB_UPDATE_DATE', db_comment='DB更新日時'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='db_update_user',
            field=models.CharField(db_column='DB_UPDATE_USER', db_comment='DB更新者', max_length=50),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expenses_id',
            field=models.BigIntegerField(db_column='EXPENSES_ID', db_comment='出費ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='is_closed',
            field=models.BooleanField(db_column='IS_CLOSED', db_comment='確定フラグ'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='member',
            field=models.ForeignKey(blank=True, db_column='MEMBER_ID', db_comment='メンバーID', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kakeibo.member'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='memo',
            field=models.CharField(blank=True, db_column='MEMO', db_comment='メモ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='shop',
            field=models.CharField(db_column='SHOP', db_comment='店名', max_length=255),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='source_file',
            field=models.CharField(blank=True, db_column='SOURCE_FILE', db_comment='取り込みファイル名', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='use_date',
            field=models.DateField(db_column='USE_DATE', db_comment='取引日'),
        ),
    ]
