# Generated by Django 4.2.30 on 2026-06-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0004_alter_expenses_amount_alter_expenses_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
    ]
